cwd: ${hydra:runtime.cwd}

batch_size: 16
num_training_steps: 200000
ko_prob: 0.5
num_relation_heads: 24
grad_norm: 1.0

optimizer:
  name: adamw
  lr: 5e-5
  betas:
    - 0.9
    - 0.98
  weight_decay: 0.01

scheduler:
  name: linear
  num_train_steps: ${num_training_steps}
  warmup_ratio: 0.01


lite:
  gpus: -1
  strategy: ddp
  precision: 32